site_name: UA Smart Signage Platform Docs
site_url: https://ua-smart-signage-platform.github.io/Documentation-Website/
nav:
  - Home: index.md
  - Documentation:
    - Introduction: 
      - About the Project: documentation/introduction.md
      - Architecture: documentation/architecture.md
      - Key Concepts: documentation/key-concepts.md
      - Tech Stack: documentation/tech-stack.md
    - Getting Started:
      - Setting Up (Development): documentation/setting-up-development.md
      - Setting Up (Production): documentation/setting-up-production.md
      - Troubleshooting: documentation/setting-up-troubleshooting.md
    - Message Protocol: documentation/message-protocol.md

  - Guidelines: guidelines.md
  - PI: pi.md
theme:
  name: material
  logo: files/logo.svg
  custom_dir: docs/material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: light green
      accent: purple
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: light green
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/UA-Smart-Signage-Platform/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/UA-Smart-Signage-Platform/"  target="_blank" rel="noopener">Projeto de Informática</a>
