site_name: UASmart Signage Platform Docs
site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
nav:
  - Welcome: index.md
  - Documentation: documentation.md
  - Project Info: project_info.md
  - Milestones: milestones.md
theme:
  name: material
  logo: files/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: light green
      accent: purple
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: light green
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/UA-Smart-Signage-Platform/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/UA-Smart-Signage-Platform/"  target="_blank" rel="noopener">Projeto de Informática</a>
